class Username
    USERNAMES = %{
        dmckenny0
        nnisius1
        edougal2
        ntwelves3
        cabsalom4
        pcaudrey5
        fcuming6
        aflippen7
        cculvey8
        gguenther9
        khesbrooka
        gkidstonb
        mfayrec
        bgiffautd
        mkuhle
        chalsallf
        uvertigang
        pgreatrakesh
        jmasseli
        tdanzeyj
        rfeakinsk
        ahightonl
        pbartenm
        agrimsdiken
        vparro
        smackessockp
        cgrayshanq
        bpringuerr
        jsybes
        bbulcht
        scopnallu
        gshortev
        istiegerw
        lhatchardx
        wemburyy
        mpenswickz
        wtrythall10
        sgreenshiels11
        cprobat12
        hyegoshin13
        ogoldingay14
        bwarnock15
        sspight16
        tdaber17
        croly18
        jalderman19
        gmulford1a
        alightwing1b
        bkollach1c
        bhabbershon1d
        dhargess1e
        bkanzler1f
        ldunrige1g
        wpittaway1h
        vewestace1i
        ltregenza1j
        hbottomley1k
        gsenecaux1l
        jandreuzzi1m
        hwillimont1n
        twoodard1o
        alye1p
        thubeaux1q
        pvittore1r
        lferonet1s
        ksibbons1t
        abonwell1u
        lcrocket1v
        asimms1w
        cguidera1x
        bodda1y
        tcollihole1z
        ametcalf20
        dlepruvost21
        agarratty22
        lmadsen23
        csleeny24
        lakroyd25
        rcreser26
        stillett27
        lgroneway28
        thollidge29
        dbeynkn2a
        mharome2b
        dcalleja2c
        jbrothwood2d
        cfilipczak2e
        mfeaveer2f
        jforstall2g
        mheigho2h
        lsergean2i
        rnansom2j
        rgrigs2k
        jgathercoal2l
        ahelbeck2m
        dokuddyhy2n
        estorks2o
        cjossel2p
        dnorcop2q
        sbakewell2r
    }

    @@usernames = USERNAMES.split(/\n/).map { |u| u.strip }.select { |u| u.length > 0 }

    def self.get_next(n = 1)
        if n == 1
            return @@usernames.pop
        else
            return @@usernames.pop(n)
        end
    end
end